## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    topology = bld.create_ns3_module('topology', ['core', 'simulator'])
    topology.source = [
        'noc-helper.cc',              
        ]

    headers = bld.new_task_gen('ns3header')
    headers.module = 'topology'
    headers.source = [
        'noc-helper.h',              
        ]

