## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    faultTolerance = bld.create_ns3_module('fault-tolerance', ['core', 'simulator'])
    faultTolerance.source = [
        'noc-fault-insertion-helper.cc',
        ]

    headers = bld.new_task_gen('ns3header')
    headers.module = 'fault-tolerance'
    headers.source = [
        'noc-fault-insertion-helper.h',
        ]

