## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    irvine = bld.create_ns3_module('irvine', ['core', 'simulator', 'router'])
    irvine.source = [
        'irvine-router.cc',
        'irvine-load-router.cc',              
        ]

    headers = bld.new_task_gen('ns3header')
    headers.module = 'irvine'
    headers.source = [
        'irvine-router.h',
        'irvine-load-router.h',              
        ]

