## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    soloadroutercomponent = bld.create_ns3_module('so-load', ['core', 'simulator', 'router'])
    soloadroutercomponent.source = [
        'so-load-router-component.cc',              
        ]

    headers = bld.new_task_gen('ns3header')
    headers.module = 'so-load'
    headers.source = [
        'so-load-router-component.h',              
        ]

