## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    nocPacket = bld.create_ns3_module('packet', ['core', 'simulator'])
    nocPacket.source = [
        'noc-header.cc',              
        'noc-packet.cc',
        'noc-packet-tag.cc',
        ]

    headers = bld.new_task_gen('ns3header')
    headers.module = 'packet'
    headers.source = [
        'noc-header.h',              
        'noc-packet.h',
        'noc-packet-tag.h',
        ]

