## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    virtualcutthrough = bld.create_ns3_module('virtual-cut-through', ['core', 'simulator', 'routing'])
    virtualcutthrough.source = [
        'vct-switching.cc',              
        ]

    headers = bld.new_task_gen('ns3header')
    headers.module = 'virtual-cut-through'
    headers.source = [
        'vct-switching.h',              
        ]

