## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    slbrouter = bld.create_ns3_module('slb-load', ['core', 'simulator', 'router'])
    slbrouter.source = [
        'slb-load-router-component.cc',              
        ]

    headers = bld.new_task_gen('ns3header')
    headers.module = 'slb-load'
    headers.source = [
        'slb-load-router-component.h',              
        ]

